// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>UnitySlippyMap.WMS</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace UnitySlippyMap.WMS {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class WMT_MS_Capabilities {
        
        private Service serviceField;
        
        private Capability capabilityField;
        
        private WMT_MS_CapabilitiesVersion versionField;
        
        private string updateSequenceField;
        
        public WMT_MS_Capabilities() {
            this.versionField = WMT_MS_CapabilitiesVersion.Item111;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Service Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Capability Capability {
            get {
                return this.capabilityField;
            }
            set {
                this.capabilityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(WMT_MS_CapabilitiesVersion.Item111)]
        public WMT_MS_CapabilitiesVersion version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string updateSequence {
            get {
                return this.updateSequenceField;
            }
            set {
                this.updateSequenceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Service {
        
        private string nameField;
        
        private string titleField;
        
        private string abstractField;
        
        private List<string> keywordListField;
        
        private OnlineResource onlineResourceField;
        
        private ContactInformation contactInformationField;
        
        private string feesField;
        
        private string accessConstraintsField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Abstract {
            get {
                return this.abstractField;
            }
            set {
                this.abstractField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Keyword", IsNullable=false)]
        public List<string> KeywordList {
            get {
                return this.keywordListField;
            }
            set {
                this.keywordListField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public OnlineResource OnlineResource {
            get {
                return this.onlineResourceField;
            }
            set {
                this.onlineResourceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public ContactInformation ContactInformation {
            get {
                return this.contactInformationField;
            }
            set {
                this.contactInformationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Fees {
            get {
                return this.feesField;
            }
            set {
                this.feesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string AccessConstraints {
            get {
                return this.accessConstraintsField;
            }
            set {
                this.accessConstraintsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class OnlineResource {
        
        private OnlineResourceType typeField;
        
        private string hrefField;
        
        public OnlineResource() {
            this.typeField = OnlineResourceType.simple;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink")]
        [System.ComponentModel.DefaultValueAttribute(OnlineResourceType.simple)]
        public OnlineResourceType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/1999/xlink")]
    public enum OnlineResourceType {
        
        /// <remarks/>
        simple,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("DCPType", Namespace="", IsNullable=false)]
    public partial class HTTP {
        
        private List<object> hTTP1Field;
        
        [System.Xml.Serialization.XmlArrayAttribute("HTTP", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Get", typeof(Get), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Post", typeof(Post), IsNullable=false)]
        public List<object> HTTP1 {
            get {
                return this.hTTP1Field;
            }
            set {
                this.hTTP1Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Get {
        
        private OnlineResource onlineResourceField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OnlineResource OnlineResource {
            get {
                return this.onlineResourceField;
            }
            set {
                this.onlineResourceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Post {
        
        private OnlineResource onlineResourceField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OnlineResource OnlineResource {
            get {
                return this.onlineResourceField;
            }
            set {
                this.onlineResourceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ContactInformation {
        
        private ContactPersonPrimary contactPersonPrimaryField;
        
        private string contactPositionField;
        
        private ContactAddress contactAddressField;
        
        private string contactVoiceTelephoneField;
        
        private string contactFacsimileTelephoneField;
        
        private string contactElectronicMailAddressField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ContactPersonPrimary ContactPersonPrimary {
            get {
                return this.contactPersonPrimaryField;
            }
            set {
                this.contactPersonPrimaryField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ContactPosition {
            get {
                return this.contactPositionField;
            }
            set {
                this.contactPositionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ContactAddress ContactAddress {
            get {
                return this.contactAddressField;
            }
            set {
                this.contactAddressField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ContactVoiceTelephone {
            get {
                return this.contactVoiceTelephoneField;
            }
            set {
                this.contactVoiceTelephoneField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ContactFacsimileTelephone {
            get {
                return this.contactFacsimileTelephoneField;
            }
            set {
                this.contactFacsimileTelephoneField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ContactElectronicMailAddress {
            get {
                return this.contactElectronicMailAddressField;
            }
            set {
                this.contactElectronicMailAddressField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ContactPersonPrimary {
        
        private string contactPersonField;
        
        private string contactOrganizationField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ContactPerson {
            get {
                return this.contactPersonField;
            }
            set {
                this.contactPersonField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ContactOrganization {
            get {
                return this.contactOrganizationField;
            }
            set {
                this.contactOrganizationField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ContactAddress {
        
        private string addressTypeField;
        
        private string addressField;
        
        private string cityField;
        
        private string stateOrProvinceField;
        
        private string postCodeField;
        
        private string countryField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AddressType {
            get {
                return this.addressTypeField;
            }
            set {
                this.addressTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string StateOrProvince {
            get {
                return this.stateOrProvinceField;
            }
            set {
                this.stateOrProvinceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Capability {
        
        private Request requestField;
        
        private List<string> exceptionField;
        
        private UserDefinedSymbolization userDefinedSymbolizationField;
        
        private Layer layerField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Request Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Format", IsNullable=false)]
        public List<string> Exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public UserDefinedSymbolization UserDefinedSymbolization {
            get {
                return this.userDefinedSymbolizationField;
            }
            set {
                this.userDefinedSymbolizationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Layer Layer {
            get {
                return this.layerField;
            }
            set {
                this.layerField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Request {
        
        private GetCapabilities getCapabilitiesField;
        
        private GetMap getMapField;
        
        private GetFeatureInfo getFeatureInfoField;
        
        private DescribeLayer describeLayerField;
        
        private GetLegendGraphic getLegendGraphicField;
        
        private GetStyles getStylesField;
        
        private PutStyles putStylesField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public GetCapabilities GetCapabilities {
            get {
                return this.getCapabilitiesField;
            }
            set {
                this.getCapabilitiesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public GetMap GetMap {
            get {
                return this.getMapField;
            }
            set {
                this.getMapField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public GetFeatureInfo GetFeatureInfo {
            get {
                return this.getFeatureInfoField;
            }
            set {
                this.getFeatureInfoField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DescribeLayer DescribeLayer {
            get {
                return this.describeLayerField;
            }
            set {
                this.describeLayerField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public GetLegendGraphic GetLegendGraphic {
            get {
                return this.getLegendGraphicField;
            }
            set {
                this.getLegendGraphicField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public GetStyles GetStyles {
            get {
                return this.getStylesField;
            }
            set {
                this.getStylesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public PutStyles PutStyles {
            get {
                return this.putStylesField;
            }
            set {
                this.putStylesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class GetCapabilities {
        
        private List<string> formatField;
        
        private List<HTTP> dCPTypeField;
        
        [System.Xml.Serialization.XmlElementAttribute("Format", Order=0)]
        public List<string> Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("DCPType", Order=1)]
        public List<HTTP> DCPType {
            get {
                return this.dCPTypeField;
            }
            set {
                this.dCPTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class GetMap {
        
        private List<string> formatField;
        
        private List<HTTP> dCPTypeField;
        
        [System.Xml.Serialization.XmlElementAttribute("Format", Order=0)]
        public List<string> Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("DCPType", Order=1)]
        public List<HTTP> DCPType {
            get {
                return this.dCPTypeField;
            }
            set {
                this.dCPTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class GetFeatureInfo {
        
        private List<string> formatField;
        
        private List<HTTP> dCPTypeField;
        
        [System.Xml.Serialization.XmlElementAttribute("Format", Order=0)]
        public List<string> Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("DCPType", Order=1)]
        public List<HTTP> DCPType {
            get {
                return this.dCPTypeField;
            }
            set {
                this.dCPTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class DescribeLayer {
        
        private List<string> formatField;
        
        private List<HTTP> dCPTypeField;
        
        [System.Xml.Serialization.XmlElementAttribute("Format", Order=0)]
        public List<string> Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("DCPType", Order=1)]
        public List<HTTP> DCPType {
            get {
                return this.dCPTypeField;
            }
            set {
                this.dCPTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class GetLegendGraphic {
        
        private List<string> formatField;
        
        private List<HTTP> dCPTypeField;
        
        [System.Xml.Serialization.XmlElementAttribute("Format", Order=0)]
        public List<string> Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("DCPType", Order=1)]
        public List<HTTP> DCPType {
            get {
                return this.dCPTypeField;
            }
            set {
                this.dCPTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class GetStyles {
        
        private List<string> formatField;
        
        private List<HTTP> dCPTypeField;
        
        [System.Xml.Serialization.XmlElementAttribute("Format", Order=0)]
        public List<string> Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("DCPType", Order=1)]
        public List<HTTP> DCPType {
            get {
                return this.dCPTypeField;
            }
            set {
                this.dCPTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PutStyles {
        
        private List<string> formatField;
        
        private List<HTTP> dCPTypeField;
        
        [System.Xml.Serialization.XmlElementAttribute("Format", Order=0)]
        public List<string> Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("DCPType", Order=1)]
        public List<HTTP> DCPType {
            get {
                return this.dCPTypeField;
            }
            set {
                this.dCPTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class UserDefinedSymbolization {
        
        private UserDefinedSymbolizationSupportSLD supportSLDField;
        
        private UserDefinedSymbolizationUserLayer userLayerField;
        
        private UserDefinedSymbolizationUserStyle userStyleField;
        
        private UserDefinedSymbolizationRemoteWFS remoteWFSField;
        
        public UserDefinedSymbolization() {
            this.supportSLDField = UserDefinedSymbolizationSupportSLD.Item0;
            this.userLayerField = UserDefinedSymbolizationUserLayer.Item0;
            this.userStyleField = UserDefinedSymbolizationUserStyle.Item0;
            this.remoteWFSField = UserDefinedSymbolizationRemoteWFS.Item0;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(UserDefinedSymbolizationSupportSLD.Item0)]
        public UserDefinedSymbolizationSupportSLD SupportSLD {
            get {
                return this.supportSLDField;
            }
            set {
                this.supportSLDField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(UserDefinedSymbolizationUserLayer.Item0)]
        public UserDefinedSymbolizationUserLayer UserLayer {
            get {
                return this.userLayerField;
            }
            set {
                this.userLayerField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(UserDefinedSymbolizationUserStyle.Item0)]
        public UserDefinedSymbolizationUserStyle UserStyle {
            get {
                return this.userStyleField;
            }
            set {
                this.userStyleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(UserDefinedSymbolizationRemoteWFS.Item0)]
        public UserDefinedSymbolizationRemoteWFS RemoteWFS {
            get {
                return this.remoteWFSField;
            }
            set {
                this.remoteWFSField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum UserDefinedSymbolizationSupportSLD {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum UserDefinedSymbolizationUserLayer {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum UserDefinedSymbolizationUserStyle {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum UserDefinedSymbolizationRemoteWFS {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Layer {
        
        private string nameField;
        
        private string titleField;
        
        private string abstractField;
        
        private List<string> keywordListField;
        
        private List<string> sRSField;
        
        private LatLonBoundingBox latLonBoundingBoxField;
        
        private List<BoundingBox> boundingBoxField;
        
        private List<Dimension> dimensionField;
        
        private List<Extent> extentField;
        
        private Attribution attributionField;
        
        private List<AuthorityURL> authorityURLField;
        
        private List<Identifier> identifierField;
        
        private List<MetadataURL> metadataURLField;
        
        private List<DataURL> dataURLField;
        
        private List<FeatureListURL> featureListURLField;
        
        private List<Style> styleField;
        
        private ScaleHint scaleHintField;
        
        private List<Layer> layersField;
        
        private LayerQueryable queryableField;
        
        private string cascadedField;
        
        private LayerOpaque opaqueField;
        
        private LayerNoSubsets noSubsetsField;
        
        private string fixedWidthField;
        
        private string fixedHeightField;
        
        public Layer() {
            this.queryableField = LayerQueryable.Item0;
            this.opaqueField = LayerOpaque.Item0;
            this.noSubsetsField = LayerNoSubsets.Item0;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Abstract {
            get {
                return this.abstractField;
            }
            set {
                this.abstractField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Keyword", IsNullable=false)]
        public List<string> KeywordList {
            get {
                return this.keywordListField;
            }
            set {
                this.keywordListField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("SRS", Order=4)]
        public List<string> SRS {
            get {
                return this.sRSField;
            }
            set {
                this.sRSField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public LatLonBoundingBox LatLonBoundingBox {
            get {
                return this.latLonBoundingBoxField;
            }
            set {
                this.latLonBoundingBoxField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("BoundingBox", Order=6)]
        public List<BoundingBox> BoundingBox {
            get {
                return this.boundingBoxField;
            }
            set {
                this.boundingBoxField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Dimension", Order=7)]
        public List<Dimension> Dimension {
            get {
                return this.dimensionField;
            }
            set {
                this.dimensionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Extent", Order=8)]
        public List<Extent> Extent {
            get {
                return this.extentField;
            }
            set {
                this.extentField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Attribution Attribution {
            get {
                return this.attributionField;
            }
            set {
                this.attributionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("AuthorityURL", Order=10)]
        public List<AuthorityURL> AuthorityURL {
            get {
                return this.authorityURLField;
            }
            set {
                this.authorityURLField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Identifier", Order=11)]
        public List<Identifier> Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("MetadataURL", Order=12)]
        public List<MetadataURL> MetadataURL {
            get {
                return this.metadataURLField;
            }
            set {
                this.metadataURLField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("DataURL", Order=13)]
        public List<DataURL> DataURL {
            get {
                return this.dataURLField;
            }
            set {
                this.dataURLField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("FeatureListURL", Order=14)]
        public List<FeatureListURL> FeatureListURL {
            get {
                return this.featureListURLField;
            }
            set {
                this.featureListURLField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Style", Order=15)]
        public List<Style> Style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public ScaleHint ScaleHint {
            get {
                return this.scaleHintField;
            }
            set {
                this.scaleHintField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Layer", Order=17)]
        public List<Layer> Layers {
            get {
                return this.layersField;
            }
            set {
                this.layersField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(LayerQueryable.Item0)]
        public LayerQueryable queryable {
            get {
                return this.queryableField;
            }
            set {
                this.queryableField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cascaded {
            get {
                return this.cascadedField;
            }
            set {
                this.cascadedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(LayerOpaque.Item0)]
        public LayerOpaque opaque {
            get {
                return this.opaqueField;
            }
            set {
                this.opaqueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(LayerNoSubsets.Item0)]
        public LayerNoSubsets noSubsets {
            get {
                return this.noSubsetsField;
            }
            set {
                this.noSubsetsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fixedWidth {
            get {
                return this.fixedWidthField;
            }
            set {
                this.fixedWidthField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fixedHeight {
            get {
                return this.fixedHeightField;
            }
            set {
                this.fixedHeightField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class LatLonBoundingBox {
        
        private string minxField;
        
        private string minyField;
        
        private string maxxField;
        
        private string maxyField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string minx {
            get {
                return this.minxField;
            }
            set {
                this.minxField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string miny {
            get {
                return this.minyField;
            }
            set {
                this.minyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maxx {
            get {
                return this.maxxField;
            }
            set {
                this.maxxField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maxy {
            get {
                return this.maxyField;
            }
            set {
                this.maxyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class BoundingBox {
        
        private string sRSField;
        
        private string minxField;
        
        private string minyField;
        
        private string maxxField;
        
        private string maxyField;
        
        private string resxField;
        
        private string resyField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SRS {
            get {
                return this.sRSField;
            }
            set {
                this.sRSField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string minx {
            get {
                return this.minxField;
            }
            set {
                this.minxField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string miny {
            get {
                return this.minyField;
            }
            set {
                this.minyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maxx {
            get {
                return this.maxxField;
            }
            set {
                this.maxxField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maxy {
            get {
                return this.maxyField;
            }
            set {
                this.maxyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string resx {
            get {
                return this.resxField;
            }
            set {
                this.resxField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string resy {
            get {
                return this.resyField;
            }
            set {
                this.resyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Dimension {
        
        private string nameField;
        
        private string unitsField;
        
        private string unitSymbolField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string unitSymbol {
            get {
                return this.unitSymbolField;
            }
            set {
                this.unitSymbolField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Extent {
        
        private string nameField;
        
        private string defaultField;
        
        private ExtentNearestValue nearestValueField;
        
        private ExtentMultipleValues multipleValuesField;
        
        private ExtentCurrent currentField;
        
        private string[] textField;
        
        public Extent() {
            this.nearestValueField = ExtentNearestValue.Item0;
            this.multipleValuesField = ExtentMultipleValues.Item0;
            this.currentField = ExtentCurrent.Item0;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ExtentNearestValue.Item0)]
        public ExtentNearestValue nearestValue {
            get {
                return this.nearestValueField;
            }
            set {
                this.nearestValueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ExtentMultipleValues.Item0)]
        public ExtentMultipleValues multipleValues {
            get {
                return this.multipleValuesField;
            }
            set {
                this.multipleValuesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ExtentCurrent.Item0)]
        public ExtentCurrent current {
            get {
                return this.currentField;
            }
            set {
                this.currentField = value;
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ExtentNearestValue {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ExtentMultipleValues {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ExtentCurrent {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Attribution {
        
        private string titleField;
        
        private OnlineResource onlineResourceField;
        
        private LogoURL logoURLField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OnlineResource OnlineResource {
            get {
                return this.onlineResourceField;
            }
            set {
                this.onlineResourceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LogoURL LogoURL {
            get {
                return this.logoURLField;
            }
            set {
                this.logoURLField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class LogoURL {
        
        private string formatField;
        
        private OnlineResource onlineResourceField;
        
        private string widthField;
        
        private string heightField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OnlineResource OnlineResource {
            get {
                return this.onlineResourceField;
            }
            set {
                this.onlineResourceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AuthorityURL {
        
        private OnlineResource onlineResourceField;
        
        private string nameField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OnlineResource OnlineResource {
            get {
                return this.onlineResourceField;
            }
            set {
                this.onlineResourceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Identifier {
        
        private string authorityField;
        
        private string[] textField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class MetadataURL {
        
        private string formatField;
        
        private OnlineResource onlineResourceField;
        
        private MetadataURLType typeField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OnlineResource OnlineResource {
            get {
                return this.onlineResourceField;
            }
            set {
                this.onlineResourceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MetadataURLType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum MetadataURLType {
        
        /// <remarks/>
        TC211,
        
        /// <remarks/>
        FGDC,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class DataURL {
        
        private string formatField;
        
        private OnlineResource onlineResourceField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OnlineResource OnlineResource {
            get {
                return this.onlineResourceField;
            }
            set {
                this.onlineResourceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class FeatureListURL {
        
        private string formatField;
        
        private OnlineResource onlineResourceField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OnlineResource OnlineResource {
            get {
                return this.onlineResourceField;
            }
            set {
                this.onlineResourceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Style {
        
        private string nameField;
        
        private string titleField;
        
        private string abstractField;
        
        private List<LegendURL> legendURLField;
        
        private StyleSheetURL styleSheetURLField;
        
        private StyleURL styleURLField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Abstract {
            get {
                return this.abstractField;
            }
            set {
                this.abstractField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("LegendURL", Order=3)]
        public List<LegendURL> LegendURL {
            get {
                return this.legendURLField;
            }
            set {
                this.legendURLField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public StyleSheetURL StyleSheetURL {
            get {
                return this.styleSheetURLField;
            }
            set {
                this.styleSheetURLField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public StyleURL StyleURL {
            get {
                return this.styleURLField;
            }
            set {
                this.styleURLField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class LegendURL {
        
        private string formatField;
        
        private OnlineResource onlineResourceField;
        
        private string widthField;
        
        private string heightField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OnlineResource OnlineResource {
            get {
                return this.onlineResourceField;
            }
            set {
                this.onlineResourceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class StyleSheetURL {
        
        private string formatField;
        
        private OnlineResource onlineResourceField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OnlineResource OnlineResource {
            get {
                return this.onlineResourceField;
            }
            set {
                this.onlineResourceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class StyleURL {
        
        private string formatField;
        
        private OnlineResource onlineResourceField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OnlineResource OnlineResource {
            get {
                return this.onlineResourceField;
            }
            set {
                this.onlineResourceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ScaleHint {
        
        private string minField;
        
        private string maxField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string max {
            get {
                return this.maxField;
            }
            set {
                this.maxField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum LayerQueryable {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum LayerOpaque {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum LayerNoSubsets {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum WMT_MS_CapabilitiesVersion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.1.1")]
        Item111,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class KeywordList {
        
        private List<string> keywordField;
        
        [System.Xml.Serialization.XmlElementAttribute("Keyword", Order=0)]
        public List<string> Keyword {
            get {
                return this.keywordField;
            }
            set {
                this.keywordField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("HTTP", Namespace="", IsNullable=false)]
    public partial class HTTP1 {
        
        private List<object> itemsField;
        
        [System.Xml.Serialization.XmlElementAttribute("Get", typeof(Get), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Post", typeof(Post), Order=0)]
        public List<object> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Exception {
        
        private List<string> formatField;
        
        [System.Xml.Serialization.XmlElementAttribute("Format", Order=0)]
        public List<string> Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
    }
}
